name = "nickczj-com"
pages_build_output_dir = "dist"
compatibility_date = "2026-05-04"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "nickczj-content"
database_id = "f2d84fed-068b-440b-950d-041836dbed0e"

[[d1_databases]]
binding = "HOMELAB_DB"
database_name = "nickczj-homelab-status"
database_id = "8c2255cc-eb0c-4aec-934d-712164282828"
