name: docker

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1.9.0 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: nickczj:latest